### ISSUE TITLE
Should the 'extra' argument be optional on graphqlHTTP?

### ISSUE THREAD

**Issue by rfgamaral** [hoangvvo/benzene#38]
Hello there 👋

I started trying out Benzene for a personal project, and I'm developing mostly in TypeScript. While following the [Getting Started](https://benzene.vercel.app/getting-started) guide I came across the following error:

![image](https://user-images.githubusercontent.com/96476/116134691-16bbab80-a6c8-11eb-9f0c-a06d38201d10.png)

I'm wondering if this `extra` argument should be optional instead? 🤔

**Comment by hoangvvo** [comment]
Yeah I think it should. Thanks for pointing out. Would you like to create a PR?

**Comment by rfgamaral** [comment]
> Yeah I think it should. Thanks for pointing out. Would you like to create a PR?

Sure, I'll open a PR soon :)
