### ISSUE TITLE
Type mismatch between graphqlHTTP({ body }) and parseGraphQLBody?

### ISSUE THREAD

**Issue by rfgamaral** [hoangvvo/benzene#40]
The Getting Started guide has this example:

```js
const server = createServer(async (req, res) => {
  const rawBody = await readBody(req);
  const result = await graphqlHTTP({
    method: req.method,
    headers: req.headers,
    body: parseGraphQLBody(rawBody, req.headers["content-type"]),
  });
  res.writeHead(result.status, result.headers);
  res.end(JSON.stringify(result.payload));
});
```

But the `body: parseGraphQLBody(rawBody, req.headers["content-type"]),` line results in a type error. Which is expected because the `body` type is `Record<string, any> | undefined`, while the `parseGraphQLBody` return type is `Record<string, any> | null`, they clearly don't match.

![image](https://user-images.githubusercontent.com/96476/116299329-75029000-a795-11eb-9098-726036b804ae.png)

If this is expected, how should it be handled? If not, can this be fixed, please?

**Comment by hoangvvo** [comment]
I think it is better for `graphqlHTTP` to also accept `body` as `null` meaning-wise  since it would explicitly be saying the body is empty. Wdyt?
