### ISSUE TITLE
Does not work with Cloudflare Workers

### ISSUE THREAD

**Issue by rfgamaral** [hoangvvo/benzene#48]
Hello again,

I'm trying to implement a GraphQL server with Benzene on Cloudflare Workers, but I'm getting an error when making a request. I can't provide a reproducible project because you'd need a Cloudflare account for that, and I'm not sure if you have one. Anyway, here's the code I have so far:

```ts
const GQL = new Benzene({ schema })

const graphqlHandler = makeHandler(GQL)

async function handleBenzeneRequest(request: HTTPRequest, rawBody: string): Promise<HTTPResponse> {
    return graphqlHandler(
        {
            method: request.method,
            headers: request.headers,
            body: parseGraphQLBody(rawBody, request.headers['content-type']),
        },
        {}
    )
}

async function readRequestBody(request: Request): Promise<string> {
    const contentType = request.headers.get('content-type')

    if (contentType?.includes('application/json')) {
        return JSON.stringify(await request.json())
    }

    return URL.createObjectURL(await request.blob())
}

async function handleRequest(request: Request): Promise<Response> {
    const result = await handleBenzeneRequest(
        {
            method: request.method,
            headers: Object.fromEntries(request.headers.entries()),
        },
        await readRequestBody(request)
    )

    console.log(result.status)
    console.log(result.headers)
    console.log(JSON.stringify(result.payload))

    return new Response(
        JSON.stringify({
            request: {
                method: request.method,
                headers: Object.fromEntries(request.headers.entries()),
            },
        }),
        {
            headers: {
                'Content-Type': 'application/json; charset=UTF-8',
            },
        }
    )
}

// eslint-disable-next-line no-restricted-globals
addEventListener('fetch', (event) => {
    event.respondWith(handleRequest(event.request))
})
```

Making a request returns the following:

```
400
[
  {
    "message": "Code generation from strings disallowed for this context"
  }
]
```

It looks like `eval()` is not supported on Cloudflare Workers, see https://github.com/cloudflare/wrangler/issues/1268, but I couldn't find any `eval` usages on my `dist` code. I also found https://github.com/intlify/vue-i18n-next/issues/198, and in there it is mentioned that `new Function('...')` is basically a different form of `eval`. Looked into my `dist` code, and there it was, a couple of references with `new Function('...')`, which come from:

* `node_modules/@hoangvvo/graphql-jit/dist/execution.js`
* `node_modules/@hoangvvo/graphql-jit/dist/resolve-info.js`

Do you think it's possible to write this differently so that the code doesn't use `eval` (and related forms), and we can use Benzene with Cloudflare Workers?

**Comment by hoangvvo** [comment]
It looks like it would be difficult to get this to work in the current situation since `graphql-jit` does rely on code generation to be fast. I think there would be two way to solve it:

- Add a mode to opt out of `graphql-jit` and use regular `graphql-js` (perf would be worse but should still be better than other graphql lib server out there)
- Add a feature in `graphql-jit` to generate the code beforehand (like during build time) in order to remove the use of `eval` during runtime.

Wdyt?

**Comment by rfgamaral** [comment]
@hoangvvo How easy is it to go for option 1 right now? Would that require many changes? I'm asking because I wanted to try that one first, benchmark the performance, and see if it actually works on Cloudflare Workers.

As for option 2, I'm not sure I understand the impact, care to provide an example of what we can do right now with `graphql-jit`, that we won't be able to do if you change code generation to build time?

**Comment by hoangvvo** [comment]
Should not be too complicated. I will give it a try then benchmark it. Feel free to start your own.

**Comment by rfgamaral** [comment]
> 
> 
> Should not be too complicated. I will give it a try then benchmark it. Feel free to start your own. Most of the changes would be in `packages/core`. Simply switch out `graphql-jit` for `graphql-js`

Not sure which `graphql-js` package are you referring to, tried [`https://github.com/graphql/graphql-js`](https://github.com/graphql/graphql-js), but it doesn't seem to have `CompiledQuery`, `compileQuery`, `isCompiledQuery`? Unless it's not as easy as to swap package names?

**Comment by hoangvvo** [comment]
Oh sorry for that. There would be some changes to be made. There is no "compiled" queries in graphql-js, so instead of first calling `compile` then `query`, we can simply use the `graphql` export from `graphql-js`.

I can give it a try when I am available soon

**Comment by rfgamaral** [comment]
Yeah, this change is a bit over my head at the moment. Looking forward to trying that change, and see those benchmarks, let me know how I can help :)

**Comment by rfgamaral** [comment]
@hoangvvo Did you make any progress here?

**Comment by hoangvvo** [comment]
@rfgamaral Do you still have any issues with Cloudflare Worker? Please let me know. Also check out the new `cloudflare-worker` example: https://github.com/hoangvvo/benzene/tree/main/examples/cloudflare-workers!

**Comment by rfgamaral** [comment]
Nope, everything seems to be working. Great job! We can close this one :)
